Landing page bottom section
sea-lene/pear-landing-page pull request #7
Opened 2024-06-20 21:19 UTC by dscreet

**Figma**
![image](https://github.com/sea-lene/pear-landing-page/assets/29370740/a55132ad-a898-42e3-91f2-1a593fcd0a46)

**Implementation**
![image](https://github.com/sea-lene/pear-landing-page/assets/29370740/f68c5fb5-75c9-4bfc-8296-d4b955ef5cf2)

- Gaps between sections can be changed according to how other parts of the landing page are for consistency.
- Hover values are temporary until standardised.
- The right section of the footer is placed about mid height of left section. I followed the design but could place it to be on the same row as the privacy and tos text.
- Do you want me to compartmentalise both the contribute section and footer?

2024-06-20 23:28 UTC, Ellahinator commented
To ensure styling consistency, I will suggest some changes.

2024-06-20 23:31 UTC, Ellahinator commented on components/try.tsx
> +            <h1 className="mb-4 text-4xl font-bold" data-aos="fade-up">
```suggestion
            <h1 className="mb-4 text-4xl font-semibold" data-aos="fade-up">
```
change the thickness of the header font to match figma and hero

2024-06-20 23:31 UTC, Ellahinator commented on components/try.tsx
> +                className="hover:text-primary-800 text-primary-700"
```suggestion
                className="hover:text-primary-800 font-medium text-primary-700"
```
Makes the clickable text easier to read.

2024-06-20 23:31 UTC, Ellahinator commented on components/try.tsx
> +                className="hover:text-primary-800 text-primary-700"
```suggestion
                className="hover:text-primary-800 font-medium text-primary-700"
```
Makes the clickable text easier to read.

2024-06-20 23:31 UTC, Ellahinator commented on components/try.tsx
> +                  className="hover:bg-primary-800 mb-4 w-full rounded-full bg-primary-700 text-white-main sm:mb-0 sm:w-auto"
```suggestion
                  className="hover:bg-primary-800 w-full rounded-full bg-primary-700 text-white-main hover:shadow-sm sm:w-auto"
```
button styling used from hero

2024-06-20 23:31 UTC, Ellahinator commented on components/try.tsx
> +                  className="w-full rounded-full border border-primary-700 text-primary-700 hover:bg-gray-100 sm:ml-4 sm:w-auto"
```suggestion
                  className="hover:border-primary-800 hover:text-primary-800 mt-2 w-full rounded-full border border-primary-700 text-primary-700 hover:shadow-sm sm:ml-4 sm:mt-0 sm:w-auto"

```
button styling used from hero

2024-06-21 04:06 UTC, Fryingpannn requested changes
Beautiful! Great job D. Last changes
- Align privacy policy, tos and the right side buttons. The all rights reserved part can be one line lower.
- For hovering, utilize what @Ellahinator did in his PR [here](https://github.com/sea-lene/pear-landing-page/pull/3/files#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2eR52). Basically, the primary on hover will look slighty darker, whereas the secondary button on hover will have it's outline look darker (with slight shadow)

2024-06-21 19:57 UTC, dscreet commented
> Beautiful! Great job D. Last changes
> 
> * Align privacy policy, tos and the right side buttons. The all rights reserved part can be one line lower.
> * For hovering, utilize what @Ellahinator did in his PR [here](https://github.com/sea-lene/pear-landing-page/pull/3/files#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2eR52). Basically, the primary button on hover will look slightly darker, whereas the secondary button on hover will have it's outline look darker (with slight shadow)

![image](https://github.com/sea-lene/pear-landing-page/assets/29370740/a00a2cb3-4b53-4c2b-9a62-dde5b9eb37b8)

2024-06-21 21:51 UTC, Fryingpannn approved these changes

2024-06-21 21:51 UTC, merged